//! Report generator for the `generate-report` subcommand.
//!
//! Collects all diagnostic information and produces a Markdown report
//! that can be attached to a GitHub issue to help contributors.
//!
//! The report NEVER contains personal information.

use anyhow::{Context, Result};
use chrono::Local;
use openrapoo_core::device::{detect_rapoo_devices, RapooDevice};
use std::path::{Path, PathBuf};

/// Run the `generate-report` subcommand.
pub async fn run_generate_report(output_path: Option<PathBuf>, open: bool) -> Result<()> {
    println!();
    println!("  Gerando relatório técnico de diagnóstico...");
    println!("  (Este relatório não contém dados pessoais.)");
    println!();

    let report_path = resolve_output_path(output_path)?;
    let report = build_report().await?;

    std::fs::write(&report_path, &report)
        .with_context(|| format!("Erro ao salvar relatório em {}", report_path.display()))?;

    println!("  ✓ Relatório salvo em:");
    println!("    {}", report_path.display());
    println!();
    println!("  Como usar:");
    println!("    Abra uma issue no GitHub e anexe este arquivo:");
    println!("    https://github.com/openrapoo/openrapoo/issues/new");
    println!();

    if open {
        // Try to open with xdg-open
        let _ = std::process::Command::new("xdg-open")
            .arg(&report_path)
            .spawn();
    }

    Ok(())
}

async fn build_report() -> Result<String> {
    let now = Local::now();
    let timestamp = now.format("%Y-%m-%d %H:%M:%S %z");
    let _date_slug = now.format("%Y-%m-%d");

    let mut report = String::new();

    // Header
    report.push_str(&format!(
        "# OpenRapoo Diagnostic Report\n\
        \n\
        **Generated:** {timestamp}  \n\
        **Tool version:** {}  \n\
        \n\
        ---\n\
        \n\
        > This report was generated automatically by `openrapoo-diag generate-report`.  \n\
        > It does not contain personal information.\n\
        > Please attach this file to a GitHub issue at: https://github.com/openrapoo/openrapoo/issues\n\
        \n",
        env!("CARGO_PKG_VERSION")
    ));

    // System information
    report.push_str("## System Information\n\n");
    report.push_str(&collect_system_info());
    report.push('\n');

    // Detected devices
    report.push_str("## Detected Rapoo Devices\n\n");
    match detect_rapoo_devices() {
        Ok(devices) if devices.is_empty() => {
            report.push_str("**No Rapoo devices detected.**\n\n");
            report.push_str("The mouse may not be connected, or the Product ID is not yet in the known list.\n\n");
            report.push_str("### Manual lsusb output\n\n");
            report.push_str("Please run the following and paste the output:\n\n");
            report.push_str("```bash\nlsusb | grep -i rapoo\nlsusb | grep -i '24ae'\n```\n\n");
        }
        Ok(devices) => {
            for (i, device) in devices.iter().enumerate() {
                report.push_str(&format!("### Device {}\n\n", i + 1));
                report.push_str(&format_device_section(device));
                report.push('\n');
            }
        }
        Err(e) => {
            report.push_str(&format!("**Error detecting devices:** {e}\n\n"));
        }
    }

    // Raw lsusb output
    report.push_str("## Raw lsusb Output\n\n");
    report.push_str("```\n");
    report.push_str(&run_command_safe("lsusb").unwrap_or_else(|e| format!("(error: {e})")));
    report.push_str("\n```\n\n");

    // /proc/bus/input/devices (filtered to Rapoo)
    report.push_str("## /proc/bus/input/devices (Rapoo entries)\n\n");
    report.push_str("```\n");
    report.push_str(&collect_proc_input_rapoo());
    report.push_str("\n```\n\n");

    // Kernel modules
    report.push_str("## Relevant Kernel Modules\n\n");
    report.push_str("```\n");
    report.push_str(&run_command_safe("lsmod").unwrap_or_else(|_| String::new()));
    report.push_str("\n```\n\n");

    // dmesg (filtered)
    report.push_str("## dmesg (Rapoo / HID entries, last boot)\n\n");
    report.push_str("```\n");
    report.push_str(&collect_dmesg_rapoo());
    report.push_str("\n```\n\n");

    // HID devices in sysfs
    report.push_str("## HID Devices in /sys/bus/hid/devices\n\n");
    report.push_str("```\n");
    report.push_str(&collect_hid_sysfs());
    report.push_str("\n```\n\n");

    // Capabilities assessment
    report.push_str("## Capability Assessment\n\n");
    report.push_str(&build_capabilities_section());

    // Footer
    report.push_str("---\n\n");
    report.push_str("*Generated by openrapoo-diag. OpenRapoo is not affiliated with Rapoo Technology Co., Ltd.*\n");

    Ok(report)
}

fn collect_system_info() -> String {
    let mut info = String::new();

    // Kernel version
    let kernel = run_command_safe("uname -r").unwrap_or_else(|_| "unknown".to_string());
    info.push_str(&format!("| Kernel | `{}` |\n", kernel.trim()));

    // Distribution
    let distro = std::fs::read_to_string("/etc/os-release")
        .ok()
        .and_then(|s| {
            s.lines().find(|l| l.starts_with("PRETTY_NAME=")).map(|l| {
                l.trim_start_matches("PRETTY_NAME=")
                    .trim_matches('"')
                    .to_string()
            })
        })
        .unwrap_or_else(|| "unknown".to_string());
    info.push_str(&format!("| Distribution | `{}` |\n", distro));

    // Architecture
    let arch = run_command_safe("uname -m").unwrap_or_else(|_| "unknown".to_string());
    info.push_str(&format!("| Architecture | `{}` |\n", arch.trim()));

    // OpenRapoo version
    info.push_str(&format!(
        "| openrapoo-diag | `{}` |\n",
        env!("CARGO_PKG_VERSION")
    ));

    format!("| Key | Value |\n|---|---|\n{info}\n")
}

fn format_device_section(device: &RapooDevice) -> String {
    let mut s = String::new();
    s.push_str("| Field | Value |\n|---|---|\n");
    s.push_str(&format!("| Name | `{}` |\n", device.name));
    s.push_str(&format!("| Model | `{}` |\n", device.model));
    s.push_str(&format!("| VID | `0x{:04X}` |\n", device.vendor_id));
    s.push_str(&format!("| PID | `0x{:04X}` |\n", device.product_id));
    s.push_str(&format!("| Connection | `{}` |\n", device.connection));
    match &device.evdev_path {
        Some(p) => s.push_str(&format!(
            "| evdev path | `{}` (accessible: {}) |\n",
            p.display(),
            device.evdev_accessible()
        )),
        None => s.push_str("| evdev path | not found |\n"),
    }
    match &device.hidraw_path {
        Some(p) => s.push_str(&format!(
            "| hidraw path | `{}` (accessible: {}) |\n",
            p.display(),
            device.hidraw_accessible()
        )),
        None => s.push_str("| hidraw path | not found |\n"),
    }
    if let Some(phys) = &device.phys {
        s.push_str(&format!("| Physical location | `{phys}` |\n"));
    }
    s
}

fn collect_proc_input_rapoo() -> String {
    let content = match std::fs::read_to_string("/proc/bus/input/devices") {
        Ok(c) => c,
        Err(e) => return format!("Error: {e}"),
    };

    // Extract blocks containing "24ae" or "rapoo" (case-insensitive)
    let mut result = String::new();
    let mut current_block = String::new();

    for line in content.lines() {
        if line.is_empty() {
            // End of block — check if it's a Rapoo device
            let lower = current_block.to_lowercase();
            if lower.contains("24ae") || lower.contains("rapoo") {
                result.push_str(&current_block);
                result.push('\n');
            }
            current_block.clear();
        } else {
            current_block.push_str(line);
            current_block.push('\n');
        }
    }

    if result.is_empty() {
        "No Rapoo entries found in /proc/bus/input/devices\n\
        (The mouse may not be connected or uses a PID not yet associated with the brand name)"
            .to_string()
    } else {
        result
    }
}

fn collect_dmesg_rapoo() -> String {
    let output = std::process::Command::new("dmesg").output();

    match output {
        Ok(out) => {
            let text = String::from_utf8_lossy(&out.stdout);
            let filtered: Vec<&str> = text
                .lines()
                .filter(|l| {
                    let lower = l.to_lowercase();
                    lower.contains("24ae")
                        || lower.contains("rapoo")
                        || lower.contains("hid-generic")
                })
                .take(50) // limit to 50 lines
                .collect();
            if filtered.is_empty() {
                "(No relevant dmesg entries found)".to_string()
            } else {
                filtered.join("\n")
            }
        }
        Err(e) => format!("(Could not run dmesg: {e})"),
    }
}

fn collect_hid_sysfs() -> String {
    let hid_base = Path::new("/sys/bus/hid/devices");
    if !hid_base.exists() {
        return "(/sys/bus/hid/devices not found)".to_string();
    }

    let entries = match std::fs::read_dir(hid_base) {
        Ok(e) => e,
        Err(e) => return format!("(Error reading /sys/bus/hid/devices: {e})"),
    };

    let mut lines = Vec::new();
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name_str = name.to_string_lossy().to_uppercase();
        if name_str.contains("24AE") {
            lines.push(name.to_string_lossy().to_string());
        }
    }

    if lines.is_empty() {
        "(No Rapoo HID devices found in /sys/bus/hid/devices)\n\
        This is expected if the mouse is not connected."
            .to_string()
    } else {
        lines.join("\n")
    }
}

fn build_capabilities_section() -> String {
    let mut s = String::new();
    s.push_str("| Feature | Status | Notes |\n");
    s.push_str("|---|---|---|\n");
    s.push_str("| Basic mouse (L/R/Middle click, scroll) | ✅ Works | Standard HID |\n");
    s.push_str("| Side buttons (Back/Forward) | ✅ Likely | BTN_SIDE / BTN_EXTRA |\n");
    s.push_str("| Horizontal scroll wheel | ⚠️ Uncertain | May be REL_HWHEEL or silent |\n");
    s.push_str("| DPI button | ⚠️ Uncertain | May generate event or be handled by firmware |\n");
    s.push_str("| Device switch button | ❌ Likely silent | Handled by firmware |\n");
    s.push_str("| Software remapping (evdev+uinput) | ✅ Planned | Phase 3 — does not need HID protocol |\n");
    s.push_str("| DPI adjustment via Linux | ❌ Not available | Requires proprietary HID protocol (Phase 8) |\n");
    s.push_str("| On-board memory config | ❌ Not available | Requires proprietary HID protocol (Phase 8) |\n");
    s.push_str("| NearLink connection | ❌ Unknown | No kernel support; may appear as 2.4 GHz |\n");
    s.push('\n');
    s
}

fn run_command_safe(cmd: &str) -> Result<String> {
    let parts: Vec<&str> = cmd.split_whitespace().collect();
    let output = std::process::Command::new(parts[0])
        .args(&parts[1..])
        .output()
        .with_context(|| format!("Failed to run '{cmd}'"))?;
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

fn resolve_output_path(given: Option<PathBuf>) -> Result<PathBuf> {
    if let Some(p) = given {
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent)?;
        }
        return Ok(p);
    }

    let base = dirs::data_local_dir()
        .unwrap_or_else(|| PathBuf::from("~/.local/share"))
        .join("openrapoo");

    std::fs::create_dir_all(&base)?;

    let filename = format!("report-{}.md", Local::now().format("%Y-%m-%d_%H-%M-%S"));
    Ok(base.join(filename))
}
